### ISSUE TITLE
Problem when there is a mix of tcp and icmp rules

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#4]
Hi @resmo I am still looking into it, but there seems to be a bug when you try to add rules to a sec group that are from different protocols.

Say you add a ssh rule and then an icmp rule….it won't work. or so it seems.
I am looking at the code right now.

**Comment by resmo** [comment]
could you give an examble?

**Comment by sebgoa** [comment]
```
  - name: Ping
    local_action:
     module: cloudstack_sg_rule
     name: foobar
     icmp_type: 8
     icmp_code: 0
     protocol: icmp

  - name: ssh
    local_action:
     module: cloudstack_sg_rule
     name: foobar
     start_port: 22
     end_port: 22
```
