### ISSUE TITLE
"No networks available" error

### ISSUE THREAD

**Issue by VoidAndAny** [resmo/ansible-cloudstack#40]
I try to create firewall rule, I always have this error : "No networks available" but the rule is created.

Here is my playbook : 

```
- hosts: all
  sudo: no
  gather_facts: no
  connection: local
  tasks:
    - cs_firewall:
        ip_address: 178.170.72.99
        start_port: 1234
        end_port: 1234
        cidr: 17.0.0.0/8
        state: present
```
