### ISSUE TITLE
Userdata support in cloudstack_vm

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#6]
@resmo thanks for your hard work on this. It's super useful
The sg, sg rules and cloudstack_vm works.

It would be great to add userdata support in the cloudstack_vm module. something like

```
- local_action:
  module: cloudstack_vm
  name: foobar
  userdata: /path/to/userdata
```

**Comment by resmo** [comment]
glad you like it! 

Concerning about userdata. I already started implementing code to support this, but needs finalising, won't be too hard. You will be able to use it like this:

``` yaml
- local_action:
    module: cloudstack_vm
    name: foobar
    user_data: "<data>"
```

or reading a file the ansible way: 

``` yaml
- local_action:
    module: cloudstack_vm
    name: foobar
    user_data: "{{ lookup('file', '/path/to/userdata') }}"
```
