### ISSUE TITLE
Problem specifying disk size on exoscale

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#7]
Hi @resmo looks like we can't specify disk size on exoscale:

this:

```
  - name: Start head-node VM
    local_action:
      module: cloudstack_vm
      name: head-node1
      template: Linux Ubuntu 14.04 LTS 64-bit 10G Disk (2014-10-28-3b8b26) 
      service_offering: Tiny
```

Gives an unknown template error. But I I use `Linux Ubuntu 14.04 LTS 64-bit` and 

```
disk_size: 10
```

It has no effect.

that's due to the naming convention of the exoscale template, which hard codes the disk sizes.

Any chance to check that ?
