### ISSUE TITLE
skip creating sec group if already created

### ISSUE THREAD

**Issue by sebgoa** [resmo/ansible-cloudstack#8]
Hi @resmo shouldn't ansible skip a task if it's already created (idempotent…).

When I create a security group that has already been created, I see the cloudstack error:

```
failed: [localhost -> 127.0.0.1] => {"failed": true}  
msg: CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 4350, u'errortext': u'Unable to create security group, a group with name foobar already exisits.'})

FATAL: all hosts have already failed -- aborting
```

I am sure there is an easy way in ansible to skip through this ?

**Comment by resmo** [comment]
Hi runseb

Yes, indeed. 

Actually I can not reproduce this error. It works for me. 

Did you use latest version? Exact task/playbook you ran?

Here is what I tested:

```
cat test.yml 
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - cloudstack_sg: name=foo
  - cloudstack_sg: name=foo
  - cloudstack_sg: name=foo state=absent
  - cloudstack_sg: name=foo state=absent
```

```
$ ansible-playbook test.yml 

PLAY [localhost] ************************************************************** 

TASK: [cloudstack_sg name=foo] ************************************************ 
changed: [localhost]

TASK: [cloudstack_sg name=foo] ************************************************ 
ok: [localhost]

TASK: [cloudstack_sg name=foo state=absent] *********************************** 
changed: [localhost]

TASK: [cloudstack_sg name=foo state=absent] *********************************** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=2    unreachable=0    failed=0    
```
